sudo: required

services:
    - docker

before_install:
    - docker build -t pd28797/react-test -f ./client/Dockerfile.dev ./client

scripts:
    - docker run pd28797/react-test npm test -- --coverage

after_success:
    - docker build -t pd28797/multi-client ./client 
    - docker build -t pd28797/multi-nginx ./nginx
    - docker build -t pd28797/multi-server ./server 
    - docker build -t pd28797/multi-worker ./worker
    
    #login to Docker
    - echo "$DOCKER_PASSWORD"  |  docker login -u "$DOCKER_ID" --password-stdin
    
    #Push images to docker-hub
    - docker push pd28797/multi-client
    - docker push pd28797/multi-nginx
    - docker push pd28797/multi-server
    - docker push pd28797/multi-worker
